<a href="https://colab.research.google.com/github/smangul1/UNIX_SUMPh_Moldova/blob/master/select.genes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving Test_gene.txt to Test_gene.txt
Saving Test.csv to Test.csv

In [2]:
import pandas as pd
df=pd.read_csv('Test.csv',";")
df.head()

     CHR        POS REF  ... Unnamed: 109 Unnamed: 110 Unnamed: 111
0   chr7   20689690   G  ...          NaN          NaN          NaN
1   chr3  186338546   C  ...          NaN          NaN          NaN
2  chr19   15484129   C  ...          NaN          NaN          NaN
3  chr19   15484129   C  ...          NaN          NaN          NaN
4   chrX   55028863   C  ...          NaN          NaN          NaN

[5 rows x 112 columns]

In [4]:
df_genes=pd.read_csv('Test_gene.txt',";")
df_genes.head()

  Gene_Name
0     ABCC8
1     ABCB5
2      ACTB
3     ACTG1
4     ACVR1

In [7]:
df_final=pd.merge(df, df_genes, on="Gene_Name")
df_final.head()

     CHR       POS REF  ... Unnamed: 109 Unnamed: 110 Unnamed: 111
0   chr7  20689690   G  ...          NaN          NaN          NaN
1  chr12  24995052   T  ...          NaN          NaN          NaN
2  chr11  73789666   G  ...          NaN          NaN          NaN
3  chr11  73789666   G  ...          NaN          NaN          NaN

[4 rows x 112 columns]

In [0]:
df_final.to_csv('gdrive/My Drive/Test_final2.csv')

In [9]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive

In [21]:
%%bash
ls
mv Test_final.csv gdrive/My\ Drive/

gdrive
sample_data
Test.csv
Test_final.csv
Test_final.txt
Test_gene.txt